import { profileUrls, type DeploymentProfile } from "./profile.js";

/** Shared by the pure restart protocol and the host deployment planner. */
export const BOT_CONTAINER_CLASS = "SwitchboardServer";
export const BOT_WORKER_DIR = "deploy/cloudflare";

/** The native application name generated by Wrangler for a named container class. */
export function containerApplicationName(script: string, className: string): string {
  return `${script}-${className.toLowerCase()}`;
}

/** One selected installation; later profile reads cannot substitute its endpoints. */
export interface ConfigConsumerTarget {
  readonly account: string;
  readonly dir: string;
  readonly containerApp: string;
  readonly healthUrl: string;
  readonly adminUrl: string;
  readonly stateWorkerUrl?: string;
}

export function configConsumerTargetFor(profile: DeploymentProfile): ConfigConsumerTarget {
  const urls = profileUrls(profile);
  return Object.freeze({
    account: profile.account,
    dir: BOT_WORKER_DIR,
    containerApp: containerApplicationName(profile.workers.bot.script, BOT_CONTAINER_CLASS),
    healthUrl: `${urls.publicBaseUrl}/healthz`,
    adminUrl: urls.botAdminRestartUrl,
    ...(urls.stateWorkerUrl !== undefined ? { stateWorkerUrl: urls.stateWorkerUrl } : {}),
  });
}
