/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    CallCard: typeof import('./src/components/run/CallCard.vue')['default']
    CostChart: typeof import('./src/components/costs/CostChart.vue')['default']
    GithubMark: typeof import('./src/components/GithubMark.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunRow: typeof import('./src/components/runs/RunRow.vue')['default']
    RunsTabs: typeof import('./src/components/runs/RunsTabs.vue')['default']
    SlackMark: typeof import('./src/components/SlackMark.vue')['default']
    SourceMark: typeof import('./src/components/runs/SourceMark.vue')['default']
    StatusDot: typeof import('./src/components/StatusDot.vue')['default']
    StepBlock: typeof import('./src/components/run/StepBlock.vue')['default']
    StepItems: typeof import('./src/components/run/StepItems.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
