/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    AssistantTurn: typeof import('./src/components/home/AssistantTurn.vue')['default']
    BrandMark: typeof import('./src/components/BrandMark.vue')['default']
    CallCard: typeof import('./src/components/run/CallCard.vue')['default']
    ChannelsPanel: typeof import('./src/components/settings/ChannelsPanel.vue')['default']
    ChatComposer: typeof import('./src/components/home/ChatComposer.vue')['default']
    ConversationRail: typeof import('./src/components/home/ConversationRail.vue')['default']
    CostChart: typeof import('./src/components/costs/CostChart.vue')['default']
    CostsByUser: typeof import('./src/components/costs/CostsByUser.vue')['default']
    DocsLink: typeof import('./src/components/DocsLink.vue')['default']
    EmptyState: typeof import('./src/components/home/EmptyState.vue')['default']
    ExpandableText: typeof import('./src/components/ExpandableText.vue')['default']
    FindingsBlock: typeof import('./src/components/unit/FindingsBlock.vue')['default']
    GithubMark: typeof import('./src/components/GithubMark.vue')['default']
    InstallationPanel: typeof import('./src/components/settings/InstallationPanel.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    McpServersPanel: typeof import('./src/components/settings/McpServersPanel.vue')['default']
    MessageFiles: typeof import('./src/components/run/MessageFiles.vue')['default']
    PendingTurnRow: typeof import('./src/components/run/PendingTurnRow.vue')['default']
    PersonTurn: typeof import('./src/components/home/PersonTurn.vue')['default']
    ReceiptChip: typeof import('./src/components/home/ReceiptChip.vue')['default']
    ReplyBlock: typeof import('./src/components/run/ReplyBlock.vue')['default']
    ResidentRow: typeof import('./src/components/residents/ResidentRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunChildrenBlock: typeof import('./src/components/run/RunChildrenBlock.vue')['default']
    RunFoldRow: typeof import('./src/components/runs/RunFoldRow.vue')['default']
    RunRow: typeof import('./src/components/runs/RunRow.vue')['default']
    RunsTabs: typeof import('./src/components/runs/RunsTabs.vue')['default']
    RunTimeline: typeof import('./src/components/run/RunTimeline.vue')['default']
    RunUnitsBlock: typeof import('./src/components/run/RunUnitsBlock.vue')['default']
    SessionSearch: typeof import('./src/components/unit/SessionSearch.vue')['default']
    SettingsLink: typeof import('./src/components/SettingsLink.vue')['default']
    SettingsTabs: typeof import('./src/components/settings/SettingsTabs.vue')['default']
    SlackMark: typeof import('./src/components/SlackMark.vue')['default']
    SourceMark: typeof import('./src/components/runs/SourceMark.vue')['default']
    SpanRow: typeof import('./src/components/run/SpanRow.vue')['default']
    StatusDot: typeof import('./src/components/StatusDot.vue')['default']
    StepBlock: typeof import('./src/components/run/StepBlock.vue')['default']
    StepItems: typeof import('./src/components/run/StepItems.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    ThreadTip: typeof import('./src/components/home/ThreadTip.vue')['default']
    TimelineSection: typeof import('./src/components/run/TimelineSection.vue')['default']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    USlideover: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTabs: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTooltip: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
